spring:
  profiles:
    default: local-gateway
  data:
    redis:
      client-type: lettuce
server:
  reactive:
    session:
      cookie:
        name: X_SESSION_ID

redis-session:
  inactive-interval: 1m

management:
  endpoints:
    web:
      exposure:
        include: health
