spring:
  config:
    activate:
      on-profile: dev
    import: configserver:http://config-server.yellowsunn.com:8080

  cloud:
    config:
      profile: ${spring.profiles.active}
      name: oauth, redis, token
  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - profile
              - email
            redirect-uri: ${micro-services.api-gateway-url}/login/oauth2/code/google
  data:
    redis:
      host: ${yellowsunn.redis.host}
      port: ${yellowsunn.redis.port}
      connect-timeout: 3000
      timeout: 1000

micro-services:
  user-service-url: http://dev-login-msa-user.yellowsunn.com:8080
  api-gateway-url: http://dev-login-msa-api-gtw.yellowsunn.com
