spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:test_db;MODE=MySQL
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        show_sql: true
