spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://dev-mysql.yellowsunn.com:3306/user_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
