name: user-service dev 배포 파이프라인
on:
  workflow_dispatch:
jobs:
  build-deploy:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: yyyyMMDDHHmmss
          utcOffset: "+09:00"
      - name: Get deploy version
        run: echo "DEV-${{ steps.current-time.outputs.formattedTime }}"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew :user-service:build

