name: user-service dev 배포 파이프라인
on:
  workflow_dispatch:
jobs:
  build-deploy:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: yyyyMMDDHHmmss
          utcOffset: "+09:00"
      - name: Get deploy version
        run: echo "deployment-version=SNAPSHOT-${{ steps.current-time.outputs.formattedTime }}" >> $GITHUB_ENV
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and Deploy image
        run: |
          ./gradlew :user-service:jib \
            -Djib.to.tags=${{ env.deployment-version }} \
            -Djib.to.auth.username="${{ secrets.DOCKER_HUB_USERNAME }}" \
            -Djib.to.auth.password="${{ secrets.DOCKER_HUB_PASSWORD }}" \
            -Djib.container.jvmFlags="-Dspring.profiles.active=dev,-Ddb-url=${{ secrets.USER_DB_URL }},-Ddb-username=${{ secrets.USER_DB_USERNAME }},-Ddb-password=${{ secrets.USER_DB_PASSWORD }}" \ 
            --stacktrace
