spring:
  config:
    activate:
      on-profile: dev
    import: configserver:http://config-server.yellowsunn.com:8080
  cloud:
    config:
      profile: ${spring.profiles.active}
      name: token
    gateway:
      routes:
        - id: user-service
          uri: http://dev-login-msa-user.yellowsunn.com:8080
          predicates:
            - Path=/api/*/users/**
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
            - RewritePath=/api/(?<version>\w+)/users/(?<path>.*), /external/api/$\{version}/users/$\{path}
