spring:
  config:
    activate:
      on-profile: dev
    import: configserver:http://config-server.yellowsunn.com:8080
  cloud:
    config:
      profile: ${spring.profiles.active}
      name: token
    gateway:
      routes:
        - id: auth-service-oauth-login
          uri: http://dev-login-msa-auth.yellowsunn.com:8080
          predicates:
            - Path=/oauth2/authorization/**
            - Method=GET, OPTIONS
          filters:
            - OAuth2CallbackUrlFilter
        - id: auth-service-oauth-code
          uri: http://dev-login-msa-auth.yellowsunn.com:8080
          predicates:
            - Path=/login/oauth2/code/**
            - Method=GET, OPTIONS
        - id: user-service
          uri: http://dev-login-msa-user.yellowsunn.com:8080
          predicates:
            - Path=/api/*/users/**
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
            - RewritePath=/api/(?<version>\w+)/users/(?<path>.*), /external/api/$\{version}/users/$\{path}
