server:
  port: 8000
spring:
  config:
    activate:
      on-profile: local
  cloud:
    gateway:
      routes:
        - id: auth-service-oauth-login
          uri: http://localhost:8001
          predicates:
            - Path=/oauth2/authorization/**
            - Method=GET, OPTIONS
          filters:
            - OAuth2CallbackUrlFilter
        - id: auth-service-oauth-code
          uri: http://localhost:8001
          predicates:
            - Path=/login/oauth2/code/**
            - Method=GET, OPTIONS
        - id: user-service
          uri: http://localhost:8002
          predicates:
            - Path=/api/*/users/**
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
            - RewritePath=/api/(?<version>\w+)/users/(?<path>.*), /external/api/$\{version}/users/$\{path}

access-token:
  secret: 4t7w!z%C*F-JaNdRgUkXp2s5v8x/A?D(G+KbPeShVmYq3t6w9z$B&E)H@McQfTjW
