spring:
  profiles:
    default: local
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-headers: "*"
            allowed-methods: "*"
      routes:
        - id: user-service
          predicates:
            - Path=/api/*/users/**
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
            - RewritePath=/api/(?<version>\w+)/users/(?<path>.*), /external/api/$\{version}/users/$\{path}

management:
  endpoints:
    web:
      exposure:
        include: health
