spring:
  config:
    activate:
      on-profile: dev
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://dev-login-msa-user.yellowsunn.com:8080
          predicates:
            - Path=/api/*/users/**
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
            - RewritePath=/api/(?<version>\w+)/users/(?<path>.*), /external/api/$\{version}/users/$\{path}

access-token:
  secret: +KbPeShVmYq3t6w9y$B&E)H@McQfTjWnZr4u7x!A%C*F-JaNdRgUkXp2s5v8y/B?

